name: model_entity_mapper_generator
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  source_gen: ^2.0.0

  model_entity_mapper_annotation:
    git:
      url: git@github.com:carlosalito/model_entity_mapper_annotation.git
      ref: main


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.5.4
  source_gen: ^2.0.0
  analyzer: ^7.5.4

flutter: